/**
 * Mock data for GitHub Pages demo mode (no backend required).
 * Mirrors the OKC roofing leads seed data from backend/seed.py.
 */
import { Campaign, Lead, Analytics } from "./api";

const NOW = new Date().toISOString();
const CAMPAIGN_ID = "demo-okc-roofing-001";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: CAMPAIGN_ID,
    name: "OKC Roofing Leads",
    icp_description:
      "Homeowners in Oklahoma City metro area (OKC, Edmond, Moore, Norman, Yukon, Mustang, Choctaw, Midwest City, Del City, Piedmont) whose roof is 10+ years old OR has visible hail/storm damage.",
    icp_parsed: {
      industries: ["Residential Real Estate", "Property Management"],
      job_titles: ["Homeowner", "Property Owner", "Property Manager"],
      pain_points: ["hail storm damage", "aging shingles", "insurance claim navigation", "active leaks"],
      locations: ["Oklahoma City, OK", "Edmond, OK", "Moore, OK", "Norman, OK", "Yukon, OK"],
      buying_signals: ["recent OKC hail event", "home built 2000-2015", "homeowner insurance active"],
    },
    status: "active",
    created_at: NOW,
    lead_count: 20,
    contacted_count: 6,
    responded_count: 3,
  },
];

export const MOCK_LEADS: Lead[] = [
  { id: "l1", campaign_id: CAMPAIGN_ID, name: "Brad Hutchinson", title: "Homeowner", company: "Hutchinson Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73034", email: "bhutchinson@gmail.com", linkedin_url: "https://linkedin.com/in/brad-hutchinson-okc", research_notes: "Roof suffered hail damage in May storm. Insurance adjuster visit scheduled. Shingles visibly cracked on south face — strong candidate for full replacement via insurance claim.", pain_points: ["hail damage from May storm", "insurance adjuster scheduled", "cracked shingles"], status: "contacted", score: 95, created_at: NOW, updated_at: NOW },
  { id: "l2", campaign_id: CAMPAIGN_ID, name: "Tammy Kowalczyk", title: "Homeowner", company: "Kowalczyk Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Moore, OK 73160", email: "tammy.k@outlook.com", linkedin_url: null, research_notes: "14-year-old roof with active leak in master bedroom. Already got an insurance quote last month — in active buying mode.", pain_points: ["active leak in master bedroom", "14yr old roof", "insurance quote obtained"], status: "responded", score: 91, created_at: NOW, updated_at: NOW },
  { id: "l3", campaign_id: CAMPAIGN_ID, name: "Derrick Sampson", title: "Homeowner", company: "Sampson Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Yukon, OK 73099", email: "dsampson82@yahoo.com", linkedin_url: "https://linkedin.com/in/derrick-sampson-yukon", research_notes: "HOA compliance notice for deteriorating roof. Home built 2004. Three neighbors on the same street recently replaced roofs — social proof is strong here.", pain_points: ["HOA compliance notice", "home built 2004", "neighbors replaced roofs"], status: "qualified", score: 88, created_at: NOW, updated_at: NOW },
  { id: "l4", campaign_id: CAMPAIGN_ID, name: "Lisa Tran", title: "Property Manager", company: "Tran Property Group", company_size: "2-5 properties", industry: "Property Management", location: "Oklahoma City, OK 73112", email: "lisa@tranpropertygroup.com", linkedin_url: "https://linkedin.com/in/lisa-tran-okc-properties", research_notes: "Manages 3 rental homes all with aging roofs. Tenant complaints about leaks. Would benefit from bulk pricing — high LTV opportunity.", pain_points: ["3 rentals with aging roofs", "tenant leak complaints", "needs bulk pricing"], status: "contacted", score: 93, created_at: NOW, updated_at: NOW },
  { id: "l5", campaign_id: CAMPAIGN_ID, name: "Mark Okafor", title: "Homeowner", company: "Okafor Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Norman, OK 73069", email: "mark.okafor@gmail.com", linkedin_url: null, research_notes: "Roof damaged in April storm. Insurance claim filed. Waiting for contractor quotes — is actively shopping right now.", pain_points: ["storm damage", "insurance claim filed", "shopping for contractors"], status: "responded", score: 97, created_at: NOW, updated_at: NOW },
  { id: "l6", campaign_id: CAMPAIGN_ID, name: "Carolyn Biggs", title: "Homeowner", company: "Biggs Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Mustang, OK 73064", email: "cbiggs.mustang@gmail.com", linkedin_url: null, research_notes: "17-year-old roof with high energy bills from poor insulation. Has seen local roofing ads but hasn't called. Needs a personal touch.", pain_points: ["17yr old roof", "high energy bills", "hasn't acted yet"], status: "new", score: 82, created_at: NOW, updated_at: NOW },
  { id: "l7", campaign_id: CAMPAIGN_ID, name: "Jason Weatherford", title: "Homeowner", company: "Weatherford Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Choctaw, OK 73020", email: "jweatherford@hotmail.com", linkedin_url: "https://linkedin.com/in/jason-weatherford-choctaw", research_notes: "Hail dents visible on gutters and roof. Neighbor filed claim and got full replacement — is aware this is possible but needs guidance on the claim process.", pain_points: ["hail dents on gutters/roof", "neighbor got replacement via insurance", "needs claim guidance"], status: "ready", score: 90, created_at: NOW, updated_at: NOW },
  { id: "l8", campaign_id: CAMPAIGN_ID, name: "Angela Norris", title: "Homeowner", company: "Norris Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Midwest City, OK 73130", email: "angela.norris.mwc@gmail.com", linkedin_url: null, research_notes: "Roof flashing failing around chimney causing water damage in attic. Home built 2001. Urgent repair needed before next storm season.", pain_points: ["failing chimney flashing", "water damage in attic", "home built 2001"], status: "new", score: 86, created_at: NOW, updated_at: NOW },
  { id: "l9", campaign_id: CAMPAIGN_ID, name: "Curtis Beaumont", title: "Homeowner", company: "Beaumont Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73003", email: "c.beaumont.okc@gmail.com", linkedin_url: "https://linkedin.com/in/curtis-beaumont-edmond", research_notes: "Roof inspection failed during refinancing. Bank is holding up closing until roof is repaired — extreme urgency, needs contractor immediately.", pain_points: ["failed roof inspection", "refinancing blocked", "bank holding up closing"], status: "contacted", score: 98, created_at: NOW, updated_at: NOW },
  { id: "l10", campaign_id: CAMPAIGN_ID, name: "Sandra Patel", title: "Property Owner", company: "Patel Rentals LLC", company_size: "5-10 properties", industry: "Property Management", location: "Oklahoma City, OK 73107", email: "sandra@patelrentals.com", linkedin_url: "https://linkedin.com/in/sandra-patel-okc", research_notes: "Portfolio of rental homes needs roof upgrades. Insurance renewal threatened by roof age. Looking for volume discount — could be a $50K+ contract.", pain_points: ["portfolio roof upgrades needed", "insurance renewal at risk", "wants volume discount"], status: "qualified", score: 94, created_at: NOW, updated_at: NOW },
  { id: "l11", campaign_id: CAMPAIGN_ID, name: "Tyler Grimes", title: "Homeowner", company: "Grimes Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Yukon, OK 73099", email: "tgrimes.yukon@gmail.com", linkedin_url: null, research_notes: "Missing shingles noticed after last storm. DIY patch failed. 11-year-old roof — replacement is likely more cost-effective than continued repairs.", pain_points: ["missing shingles post-storm", "failed DIY patch", "11yr old roof"], status: "new", score: 83, created_at: NOW, updated_at: NOW },
  { id: "l12", campaign_id: CAMPAIGN_ID, name: "Renee Calloway", title: "Homeowner", company: "Calloway Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Del City, OK 73115", email: "reneecalloway2005@yahoo.com", linkedin_url: null, research_notes: "Insurance company threatening non-renewal due to roof condition. On fixed income, needs flexible financing. Strong emotional urgency.", pain_points: ["insurance non-renewal threat", "fixed income", "needs financing options"], status: "new", score: 87, created_at: NOW, updated_at: NOW },
  { id: "l13", campaign_id: CAMPAIGN_ID, name: "Greg Ashford", title: "Homeowner", company: "Ashford Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Piedmont, OK 73078", email: "greg.ashford.okc@gmail.com", linkedin_url: "https://linkedin.com/in/greg-ashford-piedmont", research_notes: "Storm rolled through Piedmont last month. Hail damage on two sides of roof. Already has State Farm claim number — just needs a trusted contractor to work with insurer.", pain_points: ["hail damage both sides", "State Farm claim open", "needs insurance-experienced contractor"], status: "contacted", score: 96, created_at: NOW, updated_at: NOW },
  { id: "l14", campaign_id: CAMPAIGN_ID, name: "Melissa York", title: "Homeowner", company: "York Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Norman, OK 73072", email: "melissayork.norman@gmail.com", linkedin_url: null, research_notes: "13-year-old roof starting to look weathered. Planning to sell in 2-3 years and wants to increase home value. ROI angle is the key message here.", pain_points: ["13yr old roof", "planning to sell", "wants to increase home value"], status: "new", score: 79, created_at: NOW, updated_at: NOW },
  { id: "l15", campaign_id: CAMPAIGN_ID, name: "Rodney Baptiste", title: "Homeowner", company: "Baptiste Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73025", email: "rbaptiste.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/rodney-baptiste", research_notes: "Entire street got new roofs after May hail event. Insurance adjuster confirmed his damage too. Needs contractor ASAP — highest urgency lead in this campaign.", pain_points: ["whole street replaced roofs", "insurance confirmed damage", "needs contractor immediately"], status: "responded", score: 99, created_at: NOW, updated_at: NOW },
  { id: "l16", campaign_id: CAMPAIGN_ID, name: "Kim Hartley", title: "HOA Board President", company: "Stonebridge HOA", company_size: "50-unit community", industry: "Small Commercial", location: "Oklahoma City, OK 73142", email: "kim.hartley@stonebridgehoa.org", linkedin_url: "https://linkedin.com/in/kim-hartley-okc-hoa", research_notes: "Managing 12 townhome units with aging roofs. Needs bonded and insured contractor. HOA board decision — present a professional proposal.", pain_points: ["12 townhome units need roofs", "needs bonded contractor", "HOA board approval required"], status: "ready", score: 85, created_at: NOW, updated_at: NOW },
  { id: "l17", campaign_id: CAMPAIGN_ID, name: "Dale Morrison", title: "Homeowner", company: "Morrison Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Moore, OK 73170", email: "dale.morrison.moore@gmail.com", linkedin_url: null, research_notes: "Storm damaged roof in 2023. Insurance claim still open. Previous contractor ghosted him — frustrated and ready for a reliable alternative.", pain_points: ["storm damaged roof", "open insurance claim", "contractor ghosted him"], status: "new", score: 92, created_at: NOW, updated_at: NOW },
  { id: "l18", campaign_id: CAMPAIGN_ID, name: "Patricia Dunn", title: "Homeowner", company: "Dunn Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Mustang, OK 73064", email: "pdunn.mustang@outlook.com", linkedin_url: null, research_notes: "16-year-old roof. Already has two contractor quotes and is shopping for a third competitive bid. Price and trust are the deciding factors.", pain_points: ["16yr old roof", "comparing 3 contractor quotes", "price sensitive"], status: "new", score: 88, created_at: NOW, updated_at: NOW },
  { id: "l19", campaign_id: CAMPAIGN_ID, name: "Anthony Shields", title: "Homeowner", company: "Shields Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Choctaw, OK 73020", email: "anthony.shields82@gmail.com", linkedin_url: "https://linkedin.com/in/anthony-shields-okc", research_notes: "Inspection showed granule loss. Planning home renovation — roof must be done first. Good upsell opportunity for gutters and insulation.", pain_points: ["granule loss detected", "renovation sequencing", "roof before interior work"], status: "new", score: 81, created_at: NOW, updated_at: NOW },
  { id: "l20", campaign_id: CAMPAIGN_ID, name: "Brenda Castillo", title: "Homeowner", company: "Castillo Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Midwest City, OK 73110", email: "brenda.castillo.mwc@gmail.com", linkedin_url: null, research_notes: "Hail storm hit Midwest City zip code last week. Saw door hanger from competitor — actively comparing options. Speed to contact is critical here.", pain_points: ["recent zip code hail event", "competitor already reached out", "needs fast response"], status: "new", score: 90, created_at: NOW, updated_at: NOW },
];

export const MOCK_ANALYTICS: Analytics = {
  total_leads: 20,
  contacted: 6,
  responded: 3,
  qualified: 2,
  response_rate: 50.0,
  qualification_rate: 66.7,
  total_cost_usd: 0.0847,
  total_tokens: 28400,
  leads_by_status: { new: 11, researching: 0, ready: 2, contacted: 4, responded: 3, qualified: 2, disqualified: 0 },
  leads_by_industry: { "Residential Real Estate": 16, "Property Management": 2, "Small Commercial": 1 },
  messages_by_channel: { linkedin: 4, email: 3 },
  cost_by_provider: { anthropic: 0.0847 },
};
