/**
 * Mock data for GitHub Pages demo mode (no backend required).
 * Mirrors the OKC roofing leads seed data from backend/seed.py.
 */
import { Campaign, Lead, Analytics } from "./api";

const NOW = new Date().toISOString();
const CAMPAIGN_ID = "demo-okc-roofing-001";
const EDMOND_ID = "demo-edmond-audit-001";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: EDMOND_ID,
    name: "Edmond Market Audit — Roofing",
    icp_description:
      "Targeted audit of Edmond, OK homeowners (73003, 73012, 73013, 73025, 73034, 73083) with roofs 10–20 years old, active HOA communities, and documented hail exposure from the May 2023 and April 2024 OKC-area storm events. Priority on Stone Canyon, Deer Creek, Coffee Creek, Twin Creeks, Brasswood, The Ranch, and Heritage Hills neighborhoods where build years cluster 1998–2012.",
    icp_parsed: {
      industries: ["Residential Real Estate", "Property Management", "Small Commercial / HOA"],
      job_titles: ["Homeowner", "Property Owner", "HOA Board Member", "Property Manager"],
      pain_points: [
        "hail damage from May 2023 / April 2024 OKC storms",
        "aging architectural shingles (1998–2012 builds)",
        "HOA compliance notice for deteriorating roof appearance",
        "insurance non-renewal threat",
        "granule loss & energy inefficiency",
        "open insurance claim with no contractor",
      ],
      locations: [
        "Stone Canyon, Edmond OK 73025",
        "Deer Creek, Edmond OK 73012",
        "Coffee Creek, Edmond OK 73003",
        "Twin Creeks, Edmond OK 73034",
        "Brasswood, Edmond OK 73013",
        "The Ranch at Deer Creek, Edmond OK 73012",
        "Heritage Hills, Edmond OK 73003",
        "Grayhawk, Edmond OK 73025",
        "Cross Timbers, Edmond OK 73034",
        "Waterloo Road Corridor, Edmond OK 73083",
      ],
      buying_signals: [
        "home built 1998–2012 (roof age 12–26 yrs)",
        "neighbor recently replaced roof",
        "HOA letter received",
        "active State Farm / Farmers / Allstate claim",
        "refinancing or pre-listing inspection failed",
        "visible granule loss in gutters",
      ],
      exclusions: ["new construction post-2018", "apartments", "currently listed for sale with pending sale"],
      avg_home_value: "$350K–$650K",
      storm_events: ["May 2023 (EF1 hail corridor through 73025/73034)", "April 2024 (quarter-size hail, 73003/73012)"],
    },
    status: "active",
    created_at: NOW,
    lead_count: 25,
    contacted_count: 8,
    responded_count: 5,
  },
  {
    id: CAMPAIGN_ID,
    name: "OKC Roofing Leads",
    icp_description:
      "Homeowners in Oklahoma City metro area (OKC, Edmond, Moore, Norman, Yukon, Mustang, Choctaw, Midwest City, Del City, Piedmont) whose roof is 10+ years old OR has visible hail/storm damage.",
    icp_parsed: {
      industries: ["Residential Real Estate", "Property Management"],
      job_titles: ["Homeowner", "Property Owner", "Property Manager"],
      pain_points: ["hail storm damage", "aging shingles", "insurance claim navigation", "active leaks"],
      locations: ["Oklahoma City, OK", "Edmond, OK", "Moore, OK", "Norman, OK", "Yukon, OK"],
      buying_signals: ["recent OKC hail event", "home built 2000-2015", "homeowner insurance active"],
    },
    status: "active",
    created_at: NOW,
    lead_count: 20,
    contacted_count: 6,
    responded_count: 3,
  },
];

export const MOCK_LEADS: Lead[] = [
  { id: "l1", campaign_id: CAMPAIGN_ID, name: "Brad Hutchinson", title: "Homeowner", company: "Hutchinson Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73034", email: "bhutchinson@gmail.com", linkedin_url: "https://linkedin.com/in/brad-hutchinson-okc", research_notes: "Roof suffered hail damage in May storm. Insurance adjuster visit scheduled. Shingles visibly cracked on south face — strong candidate for full replacement via insurance claim.", pain_points: ["hail damage from May storm", "insurance adjuster scheduled", "cracked shingles"], status: "contacted", score: 95, created_at: NOW, updated_at: NOW },
  { id: "l2", campaign_id: CAMPAIGN_ID, name: "Tammy Kowalczyk", title: "Homeowner", company: "Kowalczyk Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Moore, OK 73160", email: "tammy.k@outlook.com", linkedin_url: null, research_notes: "14-year-old roof with active leak in master bedroom. Already got an insurance quote last month — in active buying mode.", pain_points: ["active leak in master bedroom", "14yr old roof", "insurance quote obtained"], status: "responded", score: 91, created_at: NOW, updated_at: NOW },
  { id: "l3", campaign_id: CAMPAIGN_ID, name: "Derrick Sampson", title: "Homeowner", company: "Sampson Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Yukon, OK 73099", email: "dsampson82@yahoo.com", linkedin_url: "https://linkedin.com/in/derrick-sampson-yukon", research_notes: "HOA compliance notice for deteriorating roof. Home built 2004. Three neighbors on the same street recently replaced roofs — social proof is strong here.", pain_points: ["HOA compliance notice", "home built 2004", "neighbors replaced roofs"], status: "qualified", score: 88, created_at: NOW, updated_at: NOW },
  { id: "l4", campaign_id: CAMPAIGN_ID, name: "Lisa Tran", title: "Property Manager", company: "Tran Property Group", company_size: "2-5 properties", industry: "Property Management", location: "Oklahoma City, OK 73112", email: "lisa@tranpropertygroup.com", linkedin_url: "https://linkedin.com/in/lisa-tran-okc-properties", research_notes: "Manages 3 rental homes all with aging roofs. Tenant complaints about leaks. Would benefit from bulk pricing — high LTV opportunity.", pain_points: ["3 rentals with aging roofs", "tenant leak complaints", "needs bulk pricing"], status: "contacted", score: 93, created_at: NOW, updated_at: NOW },
  { id: "l5", campaign_id: CAMPAIGN_ID, name: "Mark Okafor", title: "Homeowner", company: "Okafor Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Norman, OK 73069", email: "mark.okafor@gmail.com", linkedin_url: null, research_notes: "Roof damaged in April storm. Insurance claim filed. Waiting for contractor quotes — is actively shopping right now.", pain_points: ["storm damage", "insurance claim filed", "shopping for contractors"], status: "responded", score: 97, created_at: NOW, updated_at: NOW },
  { id: "l6", campaign_id: CAMPAIGN_ID, name: "Carolyn Biggs", title: "Homeowner", company: "Biggs Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Mustang, OK 73064", email: "cbiggs.mustang@gmail.com", linkedin_url: null, research_notes: "17-year-old roof with high energy bills from poor insulation. Has seen local roofing ads but hasn't called. Needs a personal touch.", pain_points: ["17yr old roof", "high energy bills", "hasn't acted yet"], status: "new", score: 82, created_at: NOW, updated_at: NOW },
  { id: "l7", campaign_id: CAMPAIGN_ID, name: "Jason Weatherford", title: "Homeowner", company: "Weatherford Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Choctaw, OK 73020", email: "jweatherford@hotmail.com", linkedin_url: "https://linkedin.com/in/jason-weatherford-choctaw", research_notes: "Hail dents visible on gutters and roof. Neighbor filed claim and got full replacement — is aware this is possible but needs guidance on the claim process.", pain_points: ["hail dents on gutters/roof", "neighbor got replacement via insurance", "needs claim guidance"], status: "ready", score: 90, created_at: NOW, updated_at: NOW },
  { id: "l8", campaign_id: CAMPAIGN_ID, name: "Angela Norris", title: "Homeowner", company: "Norris Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Midwest City, OK 73130", email: "angela.norris.mwc@gmail.com", linkedin_url: null, research_notes: "Roof flashing failing around chimney causing water damage in attic. Home built 2001. Urgent repair needed before next storm season.", pain_points: ["failing chimney flashing", "water damage in attic", "home built 2001"], status: "new", score: 86, created_at: NOW, updated_at: NOW },
  { id: "l9", campaign_id: CAMPAIGN_ID, name: "Curtis Beaumont", title: "Homeowner", company: "Beaumont Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73003", email: "c.beaumont.okc@gmail.com", linkedin_url: "https://linkedin.com/in/curtis-beaumont-edmond", research_notes: "Roof inspection failed during refinancing. Bank is holding up closing until roof is repaired — extreme urgency, needs contractor immediately.", pain_points: ["failed roof inspection", "refinancing blocked", "bank holding up closing"], status: "contacted", score: 98, created_at: NOW, updated_at: NOW },
  { id: "l10", campaign_id: CAMPAIGN_ID, name: "Sandra Patel", title: "Property Owner", company: "Patel Rentals LLC", company_size: "5-10 properties", industry: "Property Management", location: "Oklahoma City, OK 73107", email: "sandra@patelrentals.com", linkedin_url: "https://linkedin.com/in/sandra-patel-okc", research_notes: "Portfolio of rental homes needs roof upgrades. Insurance renewal threatened by roof age. Looking for volume discount — could be a $50K+ contract.", pain_points: ["portfolio roof upgrades needed", "insurance renewal at risk", "wants volume discount"], status: "qualified", score: 94, created_at: NOW, updated_at: NOW },
  { id: "l11", campaign_id: CAMPAIGN_ID, name: "Tyler Grimes", title: "Homeowner", company: "Grimes Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Yukon, OK 73099", email: "tgrimes.yukon@gmail.com", linkedin_url: null, research_notes: "Missing shingles noticed after last storm. DIY patch failed. 11-year-old roof — replacement is likely more cost-effective than continued repairs.", pain_points: ["missing shingles post-storm", "failed DIY patch", "11yr old roof"], status: "new", score: 83, created_at: NOW, updated_at: NOW },
  { id: "l12", campaign_id: CAMPAIGN_ID, name: "Renee Calloway", title: "Homeowner", company: "Calloway Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Del City, OK 73115", email: "reneecalloway2005@yahoo.com", linkedin_url: null, research_notes: "Insurance company threatening non-renewal due to roof condition. On fixed income, needs flexible financing. Strong emotional urgency.", pain_points: ["insurance non-renewal threat", "fixed income", "needs financing options"], status: "new", score: 87, created_at: NOW, updated_at: NOW },
  { id: "l13", campaign_id: CAMPAIGN_ID, name: "Greg Ashford", title: "Homeowner", company: "Ashford Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Piedmont, OK 73078", email: "greg.ashford.okc@gmail.com", linkedin_url: "https://linkedin.com/in/greg-ashford-piedmont", research_notes: "Storm rolled through Piedmont last month. Hail damage on two sides of roof. Already has State Farm claim number — just needs a trusted contractor to work with insurer.", pain_points: ["hail damage both sides", "State Farm claim open", "needs insurance-experienced contractor"], status: "contacted", score: 96, created_at: NOW, updated_at: NOW },
  { id: "l14", campaign_id: CAMPAIGN_ID, name: "Melissa York", title: "Homeowner", company: "York Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Norman, OK 73072", email: "melissayork.norman@gmail.com", linkedin_url: null, research_notes: "13-year-old roof starting to look weathered. Planning to sell in 2-3 years and wants to increase home value. ROI angle is the key message here.", pain_points: ["13yr old roof", "planning to sell", "wants to increase home value"], status: "new", score: 79, created_at: NOW, updated_at: NOW },
  { id: "l15", campaign_id: CAMPAIGN_ID, name: "Rodney Baptiste", title: "Homeowner", company: "Baptiste Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Edmond, OK 73025", email: "rbaptiste.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/rodney-baptiste", research_notes: "Entire street got new roofs after May hail event. Insurance adjuster confirmed his damage too. Needs contractor ASAP — highest urgency lead in this campaign.", pain_points: ["whole street replaced roofs", "insurance confirmed damage", "needs contractor immediately"], status: "responded", score: 99, created_at: NOW, updated_at: NOW },
  { id: "l16", campaign_id: CAMPAIGN_ID, name: "Kim Hartley", title: "HOA Board President", company: "Stonebridge HOA", company_size: "50-unit community", industry: "Small Commercial", location: "Oklahoma City, OK 73142", email: "kim.hartley@stonebridgehoa.org", linkedin_url: "https://linkedin.com/in/kim-hartley-okc-hoa", research_notes: "Managing 12 townhome units with aging roofs. Needs bonded and insured contractor. HOA board decision — present a professional proposal.", pain_points: ["12 townhome units need roofs", "needs bonded contractor", "HOA board approval required"], status: "ready", score: 85, created_at: NOW, updated_at: NOW },
  { id: "l17", campaign_id: CAMPAIGN_ID, name: "Dale Morrison", title: "Homeowner", company: "Morrison Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Moore, OK 73170", email: "dale.morrison.moore@gmail.com", linkedin_url: null, research_notes: "Storm damaged roof in 2023. Insurance claim still open. Previous contractor ghosted him — frustrated and ready for a reliable alternative.", pain_points: ["storm damaged roof", "open insurance claim", "contractor ghosted him"], status: "new", score: 92, created_at: NOW, updated_at: NOW },
  { id: "l18", campaign_id: CAMPAIGN_ID, name: "Patricia Dunn", title: "Homeowner", company: "Dunn Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Mustang, OK 73064", email: "pdunn.mustang@outlook.com", linkedin_url: null, research_notes: "16-year-old roof. Already has two contractor quotes and is shopping for a third competitive bid. Price and trust are the deciding factors.", pain_points: ["16yr old roof", "comparing 3 contractor quotes", "price sensitive"], status: "new", score: 88, created_at: NOW, updated_at: NOW },
  { id: "l19", campaign_id: CAMPAIGN_ID, name: "Anthony Shields", title: "Homeowner", company: "Shields Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Choctaw, OK 73020", email: "anthony.shields82@gmail.com", linkedin_url: "https://linkedin.com/in/anthony-shields-okc", research_notes: "Inspection showed granule loss. Planning home renovation — roof must be done first. Good upsell opportunity for gutters and insulation.", pain_points: ["granule loss detected", "renovation sequencing", "roof before interior work"], status: "new", score: 81, created_at: NOW, updated_at: NOW },
  { id: "l20", campaign_id: CAMPAIGN_ID, name: "Brenda Castillo", title: "Homeowner", company: "Castillo Residence", company_size: "Single Family", industry: "Residential Real Estate", location: "Midwest City, OK 73110", email: "brenda.castillo.mwc@gmail.com", linkedin_url: null, research_notes: "Hail storm hit Midwest City zip code last week. Saw door hanger from competitor — actively comparing options. Speed to contact is critical here.", pain_points: ["recent zip code hail event", "competitor already reached out", "needs fast response"], status: "new", score: 90, created_at: NOW, updated_at: NOW },
];

// ─── EDMOND AUDIT LEADS ──────────────────────────────────────────────────────
// 25 leads drawn from real Edmond neighborhoods, zip codes, HOA communities,
// and documented OKC-area storm corridors (May 2023, April 2024).
export const EDMOND_LEADS: Lead[] = [
  {
    id: "e1", campaign_id: EDMOND_ID, name: "Scott Harrington", title: "Homeowner",
    company: "Harrington Residence — Stone Canyon", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Stone Canyon, Edmond OK 73025",
    email: "scott.harrington.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/scott-harrington-edmond",
    research_notes: "2004 build in Stone Canyon — roof is 21 years old. May 2023 storm tracked directly through 73025 zip with confirmed EF1 hail. HOA sent compliance letter in March citing curling shingles visible from street. Neighbors on Flintrock Rd already have 4 new roofs. State Farm policy active.",
    pain_points: ["HOA compliance letter March 2025", "21yr old roof in May 2023 storm corridor", "State Farm policy active, claim not yet filed"],
    status: "contacted", score: 97, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e2", campaign_id: EDMOND_ID, name: "Wendy Callahan", title: "Homeowner",
    company: "Callahan Residence — Deer Creek", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Deer Creek, Edmond OK 73012",
    email: "wendy.callahan.dc@gmail.com", linkedin_url: null,
    research_notes: "2007 build in Deer Creek subdivision off Danforth. April 2024 hail event hit 73012 with quarter-size stones — she posted in Deer Creek Facebook group asking for contractor referrals. Roof is 18 years old. Farmers Insurance customer, adjuster visit pending.",
    pain_points: ["April 2024 quarter-size hail hit 73012", "18yr old roof", "adjuster visit pending — needs contractor fast"],
    status: "responded", score: 95, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e3", campaign_id: EDMOND_ID, name: "Travis Pemberton", title: "Homeowner",
    company: "Pemberton Residence — Coffee Creek", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Coffee Creek, Edmond OK 73003",
    email: "t.pemberton.okc@outlook.com", linkedin_url: "https://linkedin.com/in/travis-pemberton-okc",
    research_notes: "Coffee Creek neighborhood, built 2001. Roof is 24 years old — original shingles never replaced. April 2024 storm confirmed hail in 73003. Allstate threatened non-renewal in their last policy letter unless roof condition improves within 6 months.",
    pain_points: ["Allstate non-renewal threat", "24yr old original shingles", "April 2024 storm damage confirmed"],
    status: "qualified", score: 99, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e4", campaign_id: EDMOND_ID, name: "Ashley Drummond", title: "HOA Board President",
    company: "Coffee Creek HOA", company_size: "180-home community",
    industry: "Small Commercial / HOA", location: "Coffee Creek, Edmond OK 73003",
    email: "ashley.drummond@coffeecreekhoa.org", linkedin_url: "https://linkedin.com/in/ashley-drummond-edmond",
    research_notes: "Board president for Coffee Creek HOA — 180 homes, majority built 2000–2005. HOA has budget to assist homeowners with insurance coordination. Received 3 complaints this quarter about roof appearances violating community standards. Looking for preferred contractor relationship for the whole subdivision.",
    pain_points: ["180-home community with aging roofs", "budget for preferred contractor program", "3 complaints from HOA board about roof appearances"],
    status: "responded", score: 94, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e5", campaign_id: EDMOND_ID, name: "Kevin Morrow", title: "Homeowner",
    company: "Morrow Residence — Twin Creeks", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Twin Creeks, Edmond OK 73034",
    email: "kevin.morrow.twincreeks@gmail.com", linkedin_url: null,
    research_notes: "Twin Creeks near E Covell Rd, 2003 build. 22-year-old roof — granule loss visible in gutters after every rain. Tried one local contractor who ghosted him after the estimate. Now actively looking for a reliable roofer who works with insurance companies.",
    pain_points: ["22yr old roof with visible granule loss", "contractor ghosted after estimate", "needs insurance-savvy contractor"],
    status: "new", score: 88, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e6", campaign_id: EDMOND_ID, name: "Diane Fitzgerald", title: "Homeowner",
    company: "Fitzgerald Residence — Brasswood", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Brasswood, Edmond OK 73013",
    email: "diane.fitzgerald.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/diane-fitzgerald-edmond",
    research_notes: "Brasswood neighborhood off N Western, 2005 build, 20-year-old roof. Refinancing her home — lender's appraiser flagged roof condition as 'poor' and is requiring a contractor's assessment letter before closing. Deal is on hold. Extreme urgency — closing scheduled in 3 weeks.",
    pain_points: ["refinancing blocked by appraiser roof flag", "closing in 3 weeks", "needs contractor assessment letter ASAP"],
    status: "contacted", score: 99, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e7", campaign_id: EDMOND_ID, name: "Marcus Reid", title: "Homeowner",
    company: "Reid Residence — The Ranch at Deer Creek", company_size: "Single Family",
    industry: "Residential Real Estate", location: "The Ranch at Deer Creek, Edmond OK 73012",
    email: "marcus.reid.rdc@gmail.com", linkedin_url: "https://linkedin.com/in/marcus-reid-edmond",
    research_notes: "High-value home in The Ranch at Deer Creek ($580K est. value), built 2008. April 2024 hail confirmed. Has State Farm claim number issued — adjuster approved full replacement but homeowner hasn't selected contractor yet. Money is there, just needs to choose.",
    pain_points: ["State Farm approved full replacement", "hasn't selected contractor yet", "high-value home — needs premium service"],
    status: "contacted", score: 98, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e8", campaign_id: EDMOND_ID, name: "Stephanie Nguyen", title: "Homeowner",
    company: "Nguyen Residence — Heritage Hills", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Heritage Hills, Edmond OK 73003",
    email: "stephanie.nguyen.hh@gmail.com", linkedin_url: null,
    research_notes: "Heritage Hills near W Edmond Rd, 1999 build, 26-year-old roof. Last replacement was ~2010 with a basic 3-tab shingle. Wants to upgrade to architectural shingles this time. Planning to stay in house long-term — quality and warranty matter most to her.",
    pain_points: ["26yr old roof (replaced once in 2010 with basic 3-tab)", "wants architectural shingle upgrade", "warranty and quality are primary decision factors"],
    status: "new", score: 84, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e9", campaign_id: EDMOND_ID, name: "Bryan Ashworth", title: "Homeowner",
    company: "Ashworth Residence — Grayhawk", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Grayhawk, Edmond OK 73025",
    email: "bryan.ashworth.grayhawk@gmail.com", linkedin_url: "https://linkedin.com/in/bryan-ashworth-okc",
    research_notes: "Grayhawk subdivision near Coffee Creek Rd & Coltrane, 2006 build. May 2023 storm corridor ran through 73025. He has 3 neighbors who already replaced roofs post-storm. His wife noticed granule accumulation in downspouts. Hasn't filed a claim yet — doesn't know if he qualifies.",
    pain_points: ["in May 2023 storm corridor", "3 neighbors already replaced roofs", "doesn't know if he qualifies for insurance claim"],
    status: "ready", score: 91, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e10", campaign_id: EDMOND_ID, name: "Laura Hutchins", title: "Property Manager",
    company: "Hutchins Property Group", company_size: "6 Edmond rentals",
    industry: "Property Management", location: "Edmond OK 73034",
    email: "laura@hutchinspropertygroup.com", linkedin_url: "https://linkedin.com/in/laura-hutchins-edmond",
    research_notes: "Manages 6 single-family rentals across Edmond (73034/73025). All built 2000–2008. Four of the six had hail exposure in 2023–2024 storms. Insurance renewals coming up in Q3 — carrier already flagged two properties. Looking for contractor who can handle multiple properties and coordinate directly with insurance adjusters.",
    pain_points: ["6 Edmond rentals with aging roofs", "4 had confirmed hail exposure", "insurance renewals at risk Q3", "needs multi-property coordinator"],
    status: "responded", score: 96, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e11", campaign_id: EDMOND_ID, name: "Chad Worthington", title: "Homeowner",
    company: "Worthington Residence — Cross Timbers", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Cross Timbers, Edmond OK 73034",
    email: "chad.worthington.ct@gmail.com", linkedin_url: null,
    research_notes: "Cross Timbers near E 2nd St, built 2002. Noticed shingles starting to cup and buckle in summer heat — classic end-of-life sign on a 23-year-old roof. Energy bills have gone up 18% YoY. No storm damage claim filed — may not qualify but needs replacement regardless.",
    pain_points: ["cupping & buckling shingles — end of life", "energy bills up 18% YoY", "23yr old roof, no storm claim — needs cash sale or financing"],
    status: "new", score: 80, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e12", campaign_id: EDMOND_ID, name: "Nicole Pearson", title: "Homeowner",
    company: "Pearson Residence — Danforth Estates", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Danforth Estates, Edmond OK 73012",
    email: "nicole.pearson.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/nicole-pearson-edmond",
    research_notes: "Danforth Estates near N Coltrane, 2009 build. April 2024 storm damage confirmed by neighbor's insurance approval. Nicole hasn't filed her own claim yet — she's nervous about premium increases. Needs education on how the claim process works before she'll move forward.",
    pain_points: ["April 2024 storm damage unaddressed", "nervous about premium increase from filing claim", "needs claim process education"],
    status: "new", score: 85, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e13", campaign_id: EDMOND_ID, name: "Tim Blackwell", title: "Homeowner",
    company: "Blackwell Residence — Waterloo Road Corridor", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73083",
    email: "timblackwell.edmond@yahoo.com", linkedin_url: null,
    research_notes: "Rural Edmond near Waterloo Rd, 1998 build on 2-acre lot. Original roof — 27 years old. No HOA but very concerned about property value. Active farm policy through Oklahoma Farm Bureau — non-standard carrier, needs contractor who has worked with Farm Bureau claims before.",
    pain_points: ["27yr old original roof", "Oklahoma Farm Bureau carrier — niche claims process", "rural Edmond, 2-acre property"],
    status: "new", score: 82, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e14", campaign_id: EDMOND_ID, name: "Pam Sizemore", title: "Homeowner",
    company: "Sizemore Residence — Edmond (NW 178th)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73012",
    email: "pam.sizemore2003@gmail.com", linkedin_url: null,
    research_notes: "Near NW 178th & N Pennsylvania Ave, built 2004. Pre-listing inspection flagged the roof as 'functional but at end of expected lifespan.' Realtor told her to replace it before listing to avoid buyer negotiation. Listing in 60 days — hard deadline.",
    pain_points: ["pre-listing inspection flagged roof", "listing in 60 days — hard deadline", "realtor-motivated, not insurance-driven"],
    status: "contacted", score: 93, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e15", campaign_id: EDMOND_ID, name: "Josh Templeton", title: "HOA Board Member",
    company: "Stone Canyon HOA", company_size: "320-home community",
    industry: "Small Commercial / HOA", location: "Stone Canyon, Edmond OK 73025",
    email: "josh.templeton@stonecanyonhoa.com", linkedin_url: "https://linkedin.com/in/josh-templeton-edmond",
    research_notes: "Architectural review committee member for Stone Canyon HOA — 320 homes, built 1999–2007, majority in May 2023 storm corridor. HOA is considering establishing a preferred vendor program to streamline the roof replacement process for homeowners. Wants to evaluate 2–3 contractors. This is a subdivision-wide opportunity.",
    pain_points: ["320-home community in storm corridor", "preferred vendor program evaluation", "HOA wants to streamline replacements for all members"],
    status: "responded", score: 97, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e16", campaign_id: EDMOND_ID, name: "Donna Castleberry", title: "Homeowner",
    company: "Castleberry Residence — Quail Creek Estates", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73013",
    email: "donna.castleberry.edmond@gmail.com", linkedin_url: null,
    research_notes: "Quail Creek Estates near N MacArthur & W Memorial, built 2000. Attic inspection revealed daylight coming through in two spots — active leak waiting to happen. Husband deployed (military, Tinker AFB connection). She's making this decision solo and wants a contractor she can trust.",
    pain_points: ["daylight visible in attic — imminent leak", "deciding solo (spouse deployed)", "trust and communication are top decision factors"],
    status: "new", score: 90, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e17", campaign_id: EDMOND_ID, name: "Ryan Blackstone", title: "Homeowner",
    company: "Blackstone Residence — Deer Creek Crossing", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Deer Creek Crossing, Edmond OK 73012",
    email: "ryan.blackstone.dcc@gmail.com", linkedin_url: "https://linkedin.com/in/ryan-blackstone-edmond",
    research_notes: "Deer Creek Crossing near N Western & W Covell, built 2006. DIY inspection after April 2024 storm — found cracked ridge cap and exposed nails on field shingles. Filed claim with Nationwide, adjuster came out but undervalued the damage. Needs contractor to supplement the claim.",
    pain_points: ["Nationwide undervalued damage estimate", "needs contractor to supplement insurance claim", "cracked ridge cap + exposed nails confirmed"],
    status: "contacted", score: 95, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e18", campaign_id: EDMOND_ID, name: "Carolyn Hutchinson", title: "Homeowner",
    company: "Hutchinson Residence — Edmond (Waterford)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Waterford, Edmond OK 73034",
    email: "carolyn.hutchinson.edmond@outlook.com", linkedin_url: null,
    research_notes: "Waterford area near E 15th & Bryant Ave, built 2010. 15-year-old roof — within normal lifespan but multiple hail events recorded in 73034 zip. Insurance company (USAA) sent a roof inspection notice proactively. She hasn't responded to USAA yet and is looking for contractor guidance before engaging.",
    pain_points: ["USAA sent proactive roof inspection notice", "hasn't responded yet — needs guidance", "15yr old roof with multiple hail exposures"],
    status: "new", score: 87, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e19", campaign_id: EDMOND_ID, name: "Derek Hollingsworth", title: "Homeowner",
    company: "Hollingsworth Residence — Oak Tree", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Oak Tree, Edmond OK 73025",
    email: "derek.hollingsworth@gmail.com", linkedin_url: "https://linkedin.com/in/derek-hollingsworth-edmond",
    research_notes: "Oak Tree area near N Coltrane & Coffee Creek Rd — one of Edmond's premium golf course neighborhoods. Built 2003, home valued ~$625K. May 2023 storm hit this zip. He's had two roofers out who couldn't agree on scope. Wants a third opinion from a contractor with experience on high-value homes.",
    pain_points: ["high-value home ($625K) — needs premium contractor", "two prior estimates disagreed on scope", "May 2023 storm exposure in 73025"],
    status: "ready", score: 92, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e20", campaign_id: EDMOND_ID, name: "Tanya Brewer", title: "Homeowner",
    company: "Brewer Residence — Edmond (Santa Fe subdivision)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73003",
    email: "tanyabrewer.edmond@gmail.com", linkedin_url: null,
    research_notes: "Santa Fe subdivision near NW 178th & N Santa Fe, built 2002. Neighbors have been replacing roofs one by one since 2023 storms. Her husband thinks they're fine — she disagrees and has already gotten one estimate. Looking for a second opinion to make the case to her husband.",
    pain_points: ["needs second opinion to convince husband", "neighbors replacing roofs around her", "2002 build — likely storm damage unaddressed"],
    status: "new", score: 83, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e21", campaign_id: EDMOND_ID, name: "Greg Fontaine", title: "Homeowner",
    company: "Fontaine Residence — Edmond (Summit at Coffee Creek)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Summit at Coffee Creek, Edmond OK 73003",
    email: "greg.fontaine.summit@gmail.com", linkedin_url: "https://linkedin.com/in/greg-fontaine-edmond",
    research_notes: "Summit at Coffee Creek, 2011 build. Only 14 years old but April 2024 storm produced documented quarter-size hail in 73003. Visible dents on HVAC caps and gutters — strong indicator of roof damage. No claim filed. Works in insurance industry himself — understands claims but hasn't acted.",
    pain_points: ["quarter-size hail dents on HVAC caps & gutters", "no claim filed yet despite evidence", "works in insurance — understands the process, just needs nudge"],
    status: "new", score: 89, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e22", campaign_id: EDMOND_ID, name: "Sharon Whitfield", title: "Homeowner",
    company: "Whitfield Residence — Edmond (NW 122nd)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73013",
    email: "sharon.whitfield.edmond@yahoo.com", linkedin_url: null,
    research_notes: "Near NW 122nd & N May Ave, built 1998. 27-year-old roof — second-oldest in this audit. On fixed retirement income but has $30K home equity line available. Previously got quotes ranging from $14K–$22K and was overwhelmed. Wants simple, flat pricing with financing option.",
    pain_points: ["27yr old roof — past due", "quote range of $14K–$22K overwhelmed her", "fixed income but has HELOC — needs simple financing"],
    status: "new", score: 81, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e23", campaign_id: EDMOND_ID, name: "Chris Davenport", title: "Homeowner",
    company: "Davenport Residence — Edmond (Landrum Farms)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Landrum Farms, Edmond OK 73025",
    email: "chris.davenport.lf@gmail.com", linkedin_url: "https://linkedin.com/in/chris-davenport-edmond",
    research_notes: "Landrum Farms near E Covell & Douglas Blvd, built 2007. Roof is 18 years old. Posted in Nextdoor 'Edmond Neighbors' group two weeks ago asking for roofer recommendations — received 12 replies. High social intent signal. State Farm customer, claim not yet filed.",
    pain_points: ["posted on Nextdoor seeking roofer — high intent", "18yr old roof", "State Farm claim not yet filed"],
    status: "ready", score: 93, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e24", campaign_id: EDMOND_ID, name: "Mel Overton", title: "Homeowner",
    company: "Overton Residence — Edmond (NE 122nd / Post Oak)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Edmond OK 73013",
    email: "mel.overton.edmond@gmail.com", linkedin_url: null,
    research_notes: "Post Oak area, built 2005. Missing shingles visible from the street on north face of roof after wind event. Neighbors have already noticed and mentioned it — HOA letter likely coming. Wants to move before the letter arrives. Motivated to schedule quickly.",
    pain_points: ["missing shingles visible from street", "neighbors noticed — HOA letter expected", "wants to schedule before HOA acts"],
    status: "contacted", score: 91, created_at: NOW, updated_at: NOW,
  },
  {
    id: "e25", campaign_id: EDMOND_ID, name: "Janet Ogilvy", title: "Homeowner",
    company: "Ogilvy Residence — Edmond (Fairfield Village)", company_size: "Single Family",
    industry: "Residential Real Estate", location: "Fairfield Village, Edmond OK 73034",
    email: "janet.ogilvy.edmond@gmail.com", linkedin_url: "https://linkedin.com/in/janet-ogilvy-okc",
    research_notes: "Fairfield Village near E 33rd & S Bryant, built 2012. Only 13 years old but caught directly in April 2024 hail corridor for 73034. State Farm inspection already completed — replacement approved for $18,400. Contractor not yet selected. Just needs a good referral and a fast start date.",
    pain_points: ["State Farm approved $18,400 replacement", "just needs contractor — money is ready", "wants fast start date"],
    status: "responded", score: 99, created_at: NOW, updated_at: NOW,
  },
];

export const ALL_LEADS = [...MOCK_LEADS, ...EDMOND_LEADS];

export const MOCK_ANALYTICS: Analytics = {
  total_leads: 45,
  contacted: 14,
  responded: 8,
  qualified: 4,
  response_rate: 57.1,
  qualification_rate: 50.0,
  total_cost_usd: 0.1623,
  total_tokens: 54200,
  leads_by_status: { new: 23, researching: 0, ready: 5, contacted: 8, responded: 5, qualified: 4, disqualified: 0 },
  leads_by_industry: { "Residential Real Estate": 35, "Property Management": 4, "Small Commercial / HOA": 3, "Small Commercial": 1 },
  messages_by_channel: { linkedin: 8, email: 6 },
  cost_by_provider: { anthropic: 0.1623 },
};
